In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import numpy as np

np.array([1, 2, 3])             # → [1 2 3]

np.zeros((2,3))                 # → [[0. 0. 0.],[0. 0. 0.]]

np.ones((2,2))                  # → [[1. 1.],[1. 1.]]

np.full((2,3), 7)               # → [[7 7 7],[7 7 7]]

np.eye(3)                       # identity → [[1 0 0],[0 1 0],[0 0 1]]

np.arange(0, 10, 2)             # → [0 2 4 6 8]

np.linspace(0, 1, 5)            # → [0.   0.25 0.5  0.75 1. ]



In [2]:
import numpy as np

y = np.array([1, 2, 3])             # → [1 2 3]
print(y)
print(y.shape) # → (3,)

y1 = np.zeros((2,3))                 # → [[0. 0. 0.],[0. 0. 0.]]
print("y1:", y1)     #[[0. 0. 0.]
              # [0. 0. 0.]]
print("y1:",y1.shape) # → ((2, 3))

y3 = np.ones((1,2))                  # → [[1. 1.],[1. 1.]]
print("y3:",y3)     #[[0. 0. 0.]
              # [0. 0. 0.]]
print("y3:",y3.shape) # → ((2, 3))

np.full((2,3), 7)               # → [[7 7 7],[7 7 7]]
print("y3:",y3)     #[[0. 0. 0.]
              # [0. 0. 0.]]
print("y3:",y3.shape) # → ((2, 3))

np.eye(3)                       # identity → [[1 0 0],[0 1 0],[0 0 1]]
print("y3:",y3)     #[[0. 0. 0.]
              # [0. 0. 0.]]
print("y3:",y3.shape) # → ((2, 3))

np.arange(0, 10, 2)             # → [0 2 4 6 8]
print("y3:",y3)     #[[0. 0. 0.]
              # [0. 0. 0.]]
print("y3:",y3.shape) # → ((2, 3))

np.linspace(0, 1, 5)            # → [0.   0.25 0.5  0.75 1. ]
print("y3:",y3)     #[[0. 0. 0.]
              # [0. 0. 0.]]
print("y3:",y3.shape) # → ((2, 3))


[1 2 3]
(3,)
y1: [[0. 0. 0.]
 [0. 0. 0.]]
y1: (2, 3)
y3: [[1. 1.]]
y3: (1, 2)
y3: [[1. 1.]]
y3: (1, 2)
y3: [[1. 1.]]
y3: (1, 2)
y3: [[1. 1.]]
y3: (1, 2)
y3: [[1. 1.]]
y3: (1, 2)


a = np.array([[1,2,3],[4,5,6]])

a.shape                        # (2,3)
a.reshape(3,2)                 # [[1 2],[3 4],[5 6]]
a.flatten()                    # [1 2 3 4 5 6]
a.T                            # transpose [[1 4],[2 5],[3 6]]
np.expand_dims(a, axis=0).shape  # (1,2,3)
np.squeeze(np.array([[[5]]]))  # 5

In [3]:
a = np.array([[1,2,3],[4,5,6]])

a.shape                        # (2,3)
a.reshape(3,2)                 # [[1 2],[3 4],[5 6]]
a.flatten()                    # [1 2 3 4 5 6]
a.T                            # transpose [[1 4],[2 5],[3 6]]
np.expand_dims(a, axis=0).shape  # (1,2,3)
np.squeeze(np.array([[[5]]]))  # 5

array(5)

In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.concatenate([a,b], axis=0)  # vertical [[1 2],[3 4],[5 6],[7 8]]
np.concatenate([a,b], axis=1)  # horizontal [[1 2 5 6],[3 4 7 8]]
np.vstack([a,b])               # same as axis=0
np.hstack([a,b])               # same as axis=1
np.dstack([a,b])               # [[[1 5],[2 6]],[[3 7],[4 8]]]
np.column_stack([a[:,0], b[:,0]]) # [[1 5],[3 7]]
np.c_[a, b]                    # shortcut for column stack
np.r_[a, b]                    # shortcut for row stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
x = np.arange(9).reshape(3,3)
# x = [[0 1 2],[3 4 5],[6 7 8]]

np.split(x, 3)                 # 3 subarrays along rows
np.array_split(x, 2)           # split into 2 unequal parts
np.hsplit(x, 3)                # split into 3 columns
np.vsplit(x, 3)                # split into 3 rows

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [6]:
a = np.array([[10,20,30],[40,50,60]])

a[0,1]                         # 20 (row 0 col 1)
a[:,0]                         # [10 40] (all rows, col 0)
a[1:3,:]                       # [[40 50 60]]
a[a>25]                        # [30 40 50 60] (masking)
np.where(a>25)                 # (array([0,1,1,1]), array([2,0,1,2]))

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b                          # [5 7 9]
a * b                          # [4 10 18]
np.dot(a,b)                    # 32 (1*4+2*5+3*6)
(a @ b)                        # same → 32
np.sum(a)                      # 6
np.mean(b)                     # 5.0
np.std(b)                      # 0.816...
np.min(a), np.max(a)           # (1, 3)
np.argmax(b)                   # 2 (index of 6)
np.cumsum(a)                   # [1 3 6]
np.cumprod(a)                  # [1 2 6]

array([1, 2, 6])

In [8]:
a = np.array([3,1,2,1,3])

np.sort(a)                     # [1 1 2 3 3]
a.sort()                       # in-place sort
np.argsort(a)                  # indices [0 1 2 3 4]
np.unique(a)                   # [1 2 3]
np.unique(a, return_counts=True) # (array([1,2,3]), array([2,1,2]))

(array([1, 2, 3]), array([2, 1, 2]))

In [9]:
np.random.rand(2,2)            # uniform 0–1, shape (2,2)
np.random.randn(2,2)           # normal distribution
np.random.randint(0,10,(2,3))  # random ints 0–9
np.random.choice([10,20,30], size=5)  # sample [20 30 10 10 20]

array([30, 20, 10, 20, 10])

In [10]:
A = np.array([[3,1],[1,2]])
b = np.array([9,8])

np.linalg.inv(A)               # inverse
np.linalg.det(A)               # determinant → 5
np.linalg.eig(A)               # eigenvalues & vectors
np.linalg.solve(A,b)           # solve Ax=b

array([2., 3.])

In [11]:
a = np.array([[1,2,3],[4,5,6]])

np.save('arr.npy', a)          # save binary
np.load('arr.npy')             # load binary
np.savetxt('arr.csv', a, delimiter=',')
np.loadtxt('arr.csv', delimiter=',')


array([[1., 2., 3.],
       [4., 5., 6.]])